Fix indentation and remove unnecessary echo statements.

diff --git a/bin/envswitch b/bin/envswitch
--- a/bin/envswitch
+++ b/bin/envswitch
@@ -12,90 +12,98 @@ shopt -s nullglob
 
 function print_help()
 {
-    echo "Usage: $(basename ${0}) OPTION"
-    echo
-    echo "  -i      initialize (for use with eval)"
-    echo "  -l      list available environments"
-    echo "  -h      show this help message"
+	cat <<- EOF
+	Usage: $(basename ${0}) OPTION
+
+	-i      initialize (for use with eval)
+	-l      list available environments
+	-h      show this help message
+	EOF
 }
 
 
 function init()
 {
-    echo "envreset()"
-    echo "{"
-    echo "    if [ -n \"\${ENVSWITCH_PROFILE}\" ]"
-    echo "    then"
-    echo "        for line in \$(grep -v '^#' \"${config_dir}/\${ENVSWITCH_PROFILE}.conf\")"
-    echo "        do"
-    echo "            unset \"\${line%=*}\""
-    echo "        done"
-    echo "        unset ENVSWITCH_PROFILE"
-    echo "        export PS1=\"\${ENVSWITCH_OLDPS1}\""
-    echo "    fi"
-    echo "}"
+	cat <<- EOF
+	envreset()
+	{
+	    local -r env_file="${config_dir}/\${ENVSWITCH_PROFILE}.conf"
+	    if [ -n "\${ENVSWITCH_PROFILE}" ]
+	    then
+	        for line in \$(grep -v '^#' "\${env_file}")
+	        do
+	            unset "\${line%=*}"
+	        done
+	        unset ENVSWITCH_PROFILE
+	        export PS1="\${ENVSWITCH_OLDPS1}"
+	    fi
+	}
+	EOF
 
-    for env_file in ${config_dir}/*.conf
-    do
-        env_file_base="$(basename ${env_file%.conf})"
-        echo "${env_file_base}()"
-        echo "{"
-        echo "    if [ -n \"\${ENVSWITCH_PROFILE}\" ]"
-        echo "    then"
-        echo "        envreset"
-        echo "    fi"
-        echo "    export ENVSWITCH_PROFILE='${env_file_base}'"
-        echo "    for line in \$(grep -v '^#' ${env_file})"
-        echo "    do"
-        echo "        eval export \${line}"
-        echo "    done"
-        echo "    export ENVSWITCH_OLDPS1=\"\${PS1}\""
-        echo "    export PS1=\"(${env_file_base}) \${PS1}\""
-        echo "}"
-    done
+	for env_file in ${config_dir}/*.conf
+	do
+		env_file_base="$(basename ${env_file%.conf})"
+		cat <<- EOF
+		${env_file_base}()
+		{
+		    local -r env_file="${env_file}"
+		    if [ -n "\${ENVSWITCH_PROFILE}" ]
+		    then
+		        envreset
+		    fi
+		    export ENVSWITCH_PROFILE='${env_file_base}'
+		    for line in \$(grep -v '^#' "\${env_file}")
+		    do
+		        eval export \${line}
+		    done
+		    export ENVSWITCH_OLDPS1="\${PS1}"
+		    export PS1="(${env_file_base}) \${PS1}"
+		}
+		EOF
+	done
 }
 
 function list_environments()
 {
-    for env_file in ${config_dir}/*.conf
-    do
-        echo "$(basename ${env_file%.conf})"
-    done
+	for env_file in ${config_dir}/*.conf
+	do
+		echo "$(basename ${env_file%.conf})"
+	done
 }
 
 
 if [ ! -d "${config_dir}" ]
 then
-    umask 0077
-    mkdir -m 0700 "${config_dir}"
+	umask 0077
+	mkdir -m 0700 "${config_dir}"
 fi
 
 if [ ${#} -eq 0 ]
 then
-    echo "${0}: required option missing"
-    print_help
-    exit 1
+	echo "${0}: required option missing"
+	print_help
+	exit 1
 fi
 
 while getopts "hil" option
 do
-    case ${option} in
-        i )
-            init
-            ;;
-        h )
-            print_help
-            exit 0
-            ;;
-        l )
-            list_environments
-            exit 0
-            ;;
-        * )
-            print_help
-            exit 1
-            ;;
-    esac
+	case ${option} in
+		i )
+			init
+			;;
+		h )
+			print_help
+			exit 0
+			;;
+		l )
+			list_environments
+			exit 0
+			;;
+		* )
+			print_help
+			exit 1
+			;;
+	esac
 done
 
 shift $((${OPTIND} - 1))
