Detect and fail on incompatible option arguments.

diff --git a/bin/envswitch b/bin/envswitch
--- a/bin/envswitch
+++ b/bin/envswitch
@@ -5,8 +5,6 @@
 
 
 declare -r config_dir="${HOME}/.config/envswitch"
-declare requested_option
-
 shopt -s nullglob
 
 
@@ -72,32 +70,28 @@ function list_environments()
 }
 
 
+declare -i help_opt=0
+declare -i init_opt=0
+declare -i env_opt=0
+declare -i score=0
+
 if [ ! -d "${config_dir}" ]
 then
 	umask 0077
 	mkdir -m 0700 "${config_dir}"
 fi
 
-if [ ${#} -eq 0 ]
-then
-	echo "${0}: required option missing"
-	print_help
-	exit 1
-fi
-
 while getopts "hil" option
 do
 	case ${option} in
-		i )
-			init
-			;;
 		h )
-			print_help
-			exit 0
+			help_opt=1
+			;;
+		i )
+			init_opt=1
 			;;
 		l )
-			list_environments
-			exit 0
+			env_opt=1
 			;;
 		* )
 			print_help
@@ -107,3 +101,27 @@ do
 done
 
 shift $((${OPTIND} - 1))
+
+score=$((${help_opt} + ${init_opt} + ${env_opt}))
+if [ ${score} -eq 0 ]
+then
+	echo "${0}: required option missing"
+	print_help
+	exit 1
+elif [ ${score} -gt 1 ]
+then
+	echo "${0}: multiple options selected"
+	print_help
+	exit 1
+else
+	if [ "${help_opt}" -eq 1 ]
+	then
+		print_help
+	elif [ "${init_opt}" -eq 1 ]
+	then
+		init
+	elif [ "${env_opt}" -eq 1 ]
+	then
+		list_environments
+	fi
+fi
